server:
  port: 8085

spring:
  application:
    name: client-hello
  #profiles:
  #  active: production
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: config-server-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/